### ISSUE TITLE
Control Menu is Very Laggy

### ISSUE THREAD

**Issue by Shadowdragon019** [dozingpip/nether-create#1]
For whatever reason when I open the Control menu it lags out a ton
https://www.youtube.com/watch?v=4Tiy9muhsZ4

**Comment by dozingpip** [comment]
Can you try changing this line in your `config/topography/Topography.js`:
`setGuiBackground("images/spawn");`
to
`//setGuiBackground("images/spawn");`

and let me know if that fixes it?
I think it looks better on my end with that change, but it's hard to tell the difference.
I know it bugs out the world selection menu, so I still need to fix something, but want to know if it affects the Controls menu lag for you.
Thanks!

**Comment by dozingpip** [comment]
Replace your `config/topography/images/spawn.png` with https://github.com/dozingpip/PlayingWithFire/blob/master/config/topography/images/spawn.png (it's less than half the file size now), lmk if that works for you! Will push it with the next update if it does.

**Comment by Shadowdragon019** [comment]
Much better, the lag be gone!
